### ISSUE TITLE
Move incompatibility identifiers outside of the incompatibility struct?

### ISSUE THREAD

**Issue by mpizenberg** [pubgrub-rs/pubgrub#21]
I usually don't like when things know how they are stored. Having an `id` inside the incompatibility type is one such case. At the time of introducing the incompatibility store, I actually tried three possible designs for the recursive incompatibility type. (1) Id inside the struct, (2) id outside the struct, (3) using Rc or Box. (3) was eliminated when I ported the "no solution" reporting code, because having ids for this is very useful. But (1) and (2) are still viable options.

Current development has been done on top of (1) but I personally think (2) might be better, even though slightly more verbose. You can see the concrete difference between the two with the [comparison of the incompat-indices-in and incompat-indices-out branches](https://github.com/mpizenberg/pubgrub-rs/compare/incompat-indices-in...incompat-indices-out).

**Comment by Eh2406** [comment]
If I understand correctly all `incompatibilities` should be a copy of an item in `incompatibility_store`. That pattern is called an arena. That suggests an approach (4) use a crate like [typed_arena](https://docs.rs/typed-arena/2.0.1/typed_arena/) so that we normally work with a `&'arena Incompatibility`, specifically so `DerivedFrom` can store `&'arena Incompatibility<'arena, P, V>` and we get rid of ids entirely.

Advantages:
- no more ids
- less memory usage (as we don't have more than one copy of an `Incompatibility`)
- less clones as `&_` impls copy

Disadvantages:
- another dependency, one with unsafe code
- an `'arena` lifetime on almost everything
- gnarly (for rust) error messages when other lifetimes get (incorrectly) entangled

And yes I did make sure this worked before suggesting it. Progress at [no-ids branch](https://github.com/pubgrub-rs/pubgrub/compare/dev...no-ids).

**Comment by mpizenberg** [comment]
Oh, didn't know there was a named pattern for that :+1: 
I like the advantages and dislike the disadvantages XD. Regarding those disadvantages:
- maybe there is a safe arena version somewhere?
- if the `'arena` lifetime doesn't creep up to the exposed API that could be acceptable even though quite annoying

Also, I'm not sure I'm getting what is done to identify incompatibilities that appears multiple times in the derivation tree (the `find_shared_ids` method). Is it using their memory addresses as identifiers? (If you want to know a bit more about what those identifiers are used for, you can have look at the [WIP section of the guide about it](https://5f9361df4b834771d598a7b3--pubgrub-rs-guide.netlify.app/pubgrub_crate/custom_report.html))

**Comment by Eh2406** [comment]
> Is it using their memory addresses as identifiers?

Yes. It is tricky to find a good alternative. We can do a linear scan of the `Arena` and use the index. But we would have to do it every time because `Incompatibility` can not impl `Hash` nor `Ord`, so `___Map<&'arena Incompatibility, Id>` is out. Whatever we chews, it needs to become a method with good documentation of what it is doing.

> if the `'arena` lifetime doesn't creep up to the exposed API that could be acceptable even though quite annoying
 
Yes, it should not be in the public interface. If for no other reason then that means that the `Arena` with all the temporary `Incompatibility`s will not yet have been dropped.

> maybe there is a safe arena version somewhere?

The fundamental method provided by `typed-arena` is `alloc(&self, value: T) -> &mut T`. Somehow any `arena` with that method needs garantly that `T` will not be moved while `self` exists. I think that is fundamentally going to require unsafe somewhere.

There are lots of other `arena` crates with different apis. For example there is [id-arena](https://docs.rs/crate/id-arena/2.2.1) with no unsafe, but it's `alloc` does not return a reference it returns an opaque `ID`. We'd need to pass around a reference to the `Arena` for any place that wants to look at the contents of the `Incompatibility`. Fundamentally this is a variation on approach (2), and definitely worth considering if we decide on approach (2).

**Comment by mpizenberg** [comment]
I see, I don't think it's safe to assume that ids from addresses will remain the same between the `find_shared_ids` and `incompat.build_derivation_tree` even if its just after. We should probably postpone a change like that for later. Keep the issue around and come back to this when all the rest has stabilized since it shouldn't affect exposed API.

**Comment by Eh2406** [comment]
We can definitely leave it for later! It was just another option to keep in mind. (Especially in related conversations around the use of `pub` for `id`s.)
> I don't think it's safe to assume that ids from addresses will remain the same

I think the `Incompatibility` can't move while we have a reference to it. At any time we can dereference any old copy of the reference we have. If it has been moved behind our back, then :boom: Undefined behavior in safe code. Whether I got the incantation correctly to get the location of the `Incompatibility` and not some other location... is a place to be careful.

**Comment by Eh2406** [comment]
To keep memory usage minimal, I like the idea of having only one copy of things and using a reference to the canonical copy.
I can see 2 long term approaches that has that property.
- [id-arena || vec](https://docs.rs/crate/id-arena/2.2.1) This is a type safe version of design (2). `incompatibility_store` holds the only copy, everything else use a `incompatIdx`. On the occasions when we need to look at the incompatibility we run `self.incompatibility_store.get(incompatIdx)`. Pro, safe and not so different from what we are doing now. And I can see using it on some other types in our system, depending on how the data structures develop.
- [typed_arena](https://docs.rs/typed-arena/2.0.1/typed_arena/) This is [design (4)](https://github.com/pubgrub-rs/pubgrub/issues/21#issuecomment-715665504). Pro, less code to access an incompatibility, no copying of incompatibilities as the arena grows. We can ensure that we get the memory location code correct by testing a commit that still has the IDs and makes sure they always agree. Cons, have already been discussed.

Is now a good time to come back to investigating this? If so what do we want to try next? Make a proof of concept PR of both and compare perf?

**Comment by Eh2406** [comment]
I played with it.
The [typed-ids](https://github.com/pubgrub-rs/pubgrub/tree/typed-ids) branch has the code for one approach. The first commit is using the `id-arena` crate the second roles our own.
The [no-ids](https://github.com/pubgrub-rs/pubgrub/tree/no-ids) batch has the `typed_arena` approach.

Both have similar and very good perf / dhat results. Both involve a lot of code chern. One thanks to dragging `&store` to lots of functions, the other dragging an `'arena` lifetime into everything. Depending on what you think, I am leaning toward opening a PR from the `typed-ids` branch.

**Comment by mpizenberg** [comment]
I see, I'd go forward with the typed-ids approach too so I'll review that PR now. Thanks!
