### ISSUE TITLE
Other functionality from the Dart implementation

### ISSUE THREAD

**Issue by Eh2406** [pubgrub-rs/pubgrub#39]
The Dart implementation has some functionality that is not in the blog post. I do not know the the Dart implementation thoroughly, so if I missed something feel free to add to these notes.

- "features" (in [cargo](https://doc.rust-lang.org/cargo/reference/features.html)) are a form of build flag that can enable optional dependencies. They were added to the dart implementation but where never exposed in the user interface.
- "replacements" (in cargo the [patch section](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html?highlight=replac#the-patch-section) and the [replace](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html?highlight=replac#the-replace-section)) are a way to substitute the code for one package with some other code. In dart it is called [dependency-overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides).
- "pre-release" (in [cargo](https://doc.rust-lang.org/cargo/reference/resolver.html?highlight=pre#pre-releases)) is part of the semver spec that allows versions like `1.0.0-alpha`. I don't know how dart supports this but I believe it does.
- "lockfiles" is a way to encode and reuse the output from a previous resolution, and even if the dependencies have changed keep things as similar as possible. In Cargo this is done by a set of heuristics that are part of the dependency provider, and it is a mess. In dart this is somehow worked into the resolver. 

This is all functionality that Cargo and Dart have where the next steps for exploring is "look at how Dart did it". Even if Darts way of doing things does not work for Cargo it is probably worth making available in the library for other use cases.
I will be writing up a separate issue for functionality that Cargo has that Dart does not.

**Comment by mpizenberg** [comment]
Nice! I'll add some of my thoughts regarding those.

### Lockfiles

I can see different levels of support for this functionality, depending on the level of trust we give to the lockfile.

- If we trust it completely, there is nothing to do, resolution has already being done, and there is no need to call pubgrub at all.
- If we don't, we could just verify that the set of packages is correct with pubgrub. Here nothing to change either in pubgrub. The `DependencyProvider` implementation just has to put versions from the lockfile at the beginning of the list of versions for a given package. When resolving is done, we just check that the solution equals the lockfile versions.

### Pre-release

Pre-releases are versions. So the main question here is if the `Version` trait can express the kind of behavior that pre-releases are supposed to follow. Under which conditions are pre-releases selectable by Cargo? What kind of constraints enable them being picked in `Cargo.toml`? is it only for direct dependencies, or can they also being picked for indirect dependencies? How does that play with the patches?

### Patch

It seems that a patch replaces directly the list of existing versions of a package by one explicitely provided in the patch. I tend to believe this is then just a matter of doing exactly that a `DependencyProvider` implementation.

### Replace

Are the versions specified authorized to be new (non-existing in crates)? If not, this is just a matter of adjusting the `get_dependencies` method of a `DependencyProvider` implementation. If yes, it also needs to adjust the `list_available_versions`.

### features

It seems that features effectively change the dependencies of a given package.

Let's start with a few thoughts to imagine if this could be done without changing anything in pubgrub. We could consider that every feature is actually a different package. The package "a" is different from the package "a-feat" since it has a different set of dependencies. So for direct dependencies, there is no issue. Now the question is how is this dealt with in cargo when multiple packages in the dependency tree are asking for "a" and "a-feat"? What should happen if they are required at the same version ("a:1", "a-feat:1") or at a different version ("a:1", "a-feat:1.2"). The obvious thing of considering "a" and "a-feat" independent packages does not care. But it means that cargo needs to build them with different names. Is it what Cargo currently does?

If that simple solution of just making features different packages is compatible with Cargo behavior, then the only downside is that the number of packages increases with combinations of features. But that isn't even an issue since the `DependencyProvider` could store them in a specific way (that doesn't grow the complexity) and present them in another way.

**Comment by mpizenberg** [comment]
It seems that most of this can be experimented with by trying to build the most adequate implementations of a `Package`, `Version` and `DependencyProvider` traits. Let's start by doing that in another repo like `cargo-pubgrub` in the new org once that's created and see how far we can go with it.

**Comment by aleksator** [comment]
### Lockfiles

> I can see different levels of support for this functionality, depending on the level of trust we give to the lockfile.
> -   If we trust it completely, there is nothing to do, resolution has already being done, and there is no need to call pubgrub at all.
> -   If we don't, we could just verify that the set of packages is correct with pubgrub. Here nothing to change either in pubgrub. The DependencyProvider implementation just has to put versions from the lockfile at the beginning of the list of versions for a given package. When resolving is done, we just check that the solution equals the lockfile versions.

The problem comes when updating a set of dependencies (bumping dependency version in Cargo.toml) with a lockfile present. The packages should be kept as closely as possible to specified lockfile while still performing needed upgrades.

### Patch

> It seems that a patch replaces directly the list of existing versions of a package by one explicitely provided in the patch. I tend to believe this is then just a matter of doing exactly that a DependencyProvider implementation.

I agree.

### Pre-release

Interestingly handling of pre-release versions still seems to be an open question for cargo: https://github.com/rust-lang/cargo/issues/2222.

Currently they do the following (correct me if I'm wrong):
> Under which conditions are pre-releases selectable by Cargo?

Only if specifically requested I believe.

> is it only for direct dependencies, or can they also being picked for indirect dependencies?

Only for those packages that requested the prerelease.

### features

> Now the question is how is this dealt with in cargo when multiple packages in the dependency tree are asking for "a" and "a-feat"? What should happen if they are required at the same version ("a:1", "a-feat:1")

Everyone would be given "a-feat" even when they asked for just "a".
That's the whole point of `features`: enabling additional functionality without impacting those who don't need it. That's why `features` should only be additive.

> or at a different version ("a:1", "a-feat:1.2").

I'm not sure if cargo will produce exactly that ("a:1", "a-feat:1.2") or would do not optimal ("a-feat:1", "a-feat:1.2"), i.e. enable features for everyone.

### Private dependencies

Not mentioned in this thread, but mentioned on Zulip. I believe those could also be handled by DependencyProvider without the algorithm having to care where exactly the dependencies come from.

**Comment by mpizenberg** [comment]
> The problem comes when updating a set of dependencies (bumping dependency version in Cargo.toml) with a lockfile present. The packages should be kept as closely as possible to specified lockfile while still performing needed upgrades.

Interesting! Is there a formal "distance" specification in the space of versions. A way of ranking different choices?

In case versions in the lockfile are compatible with changes in `Cargo.toml` there is nothing special to do. In case only one package changes to a new constraint incompatible with the locked version, it's also straightforward. In case multiple packages change there could be plenty of different approaches. Here are some ideas.

1) The efficient-driven approach: don't care, we just put locked versions first in the list of available versions. If they are picked as compatible, great, if they aren't, well that's life. By design (locked versions are tried first) it will result in few changes.
2) The comprehensive approach: pick a distance metric (like 0 if exact the same, 1 if different, or 1 for patch bump, 2 for minor bump, etc. just any metric), then use a hashmap that keeps the order of packages (we had discussed that in https://github.com/mpizenberg/pubgrub-rs/pull/13#issuecomment-704117807) and run the solver for every order possible of those packages, keep the one with the lowest distance to the lockfile. That is obviously a waste of time, but it's the most accurate way to get a "minimal changes" new lockfile.
3) The random reward-driven approach: randomly sample a few different orders, at least one per different package first, and leverage the `should_cancel` by providing some feedback, like current decisions in the partial solution to only continue the most rewarding runs being done and cut the others. This may not play well with backtracking though since we may keep a runner on a path that currently has a lower distance, but then will have to backtrack.

I think in most cases, (1) is the best choice. It's also a choice that doesn't require any change to the current state of pubgrub.

**Comment by aleksator** [comment]
> Interesting! Is there a formal "distance" specification in the space of versions. A way of ranking different choices?

Oh, it's rather binary: is it possible to use the exact version specified in the lockfile? Yes -> use it, no -> use normal dependency resolution ("unlock it").

**Comment by aleksator** [comment]
So if my understanding is correct, the strategy 1 should be used and indeed the support of lock files delegated to `DependencyProvider` implementation.

**Comment by Eh2406** [comment]
So having seen the discussion so far I agree that when we are in an org it is worth making a separate repo to experiment with adding this functionality without changes to `pubgrub-rs`. I still think that Natalie decided to work these things into the the Dart implementation and so we should check if she had a good reason. It may be that for separation of concerns reasons we don't want to copy her decision, but I would like to understand it.

Instead of responding to the conversation on each feature, I will wait until we have that new repo and make a separate issue for each. If that is ok with you?

**Comment by aleksator** [comment]
@Eh2406 Would you still like to create separate issues for these features? Or is it going to be in another repository?

**Comment by Eh2406** [comment]
Oops... it slipped off my radar. I will make a new repo and add the issues there. I hope to get to it tomorrow.

**Comment by Eh2406** [comment]
Repo made and conversation moved. I will close this to drive the conversation there. I will work on writing up responses tomorrow.
