### ISSUE TITLE
Unexpected display formatting for ranges

### ISSUE THREAD

**Issue by lpil** [pubgrub-rs/pubgrub#85]
Hello!

I found the printing of this range surprising.

```rust
let one = MyVersion::new(1, 0, 0);
let two = MyVersion::new(2, 0, 0);
let three = MyVersion::new(3, 0, 0);
let range = Range::higher_than(one)
    .intersection(&Range::strictly_lower_than(two))
    .union(&Range::higher_than(three));
println!("{}", range);
```

The output here is `[ 1.0.1, 2.0.0 [  [ 4.0.0, ∞ [`, which is an unfamiliar syntax to me and I think my users will find it confusing. I was expecting something closer to `> 1.0.0 and < 2.0.0 or > 4.0.0`
What syntax is this? Would a more widely known syntax be preferable?

Thank you,
Louis

**Comment by mpizenberg** [comment]
Hey, yeah to be honest not much effort was poured into the error reporting side. Mostly because this hasn't had a strong use case yet where errors are commons yet.

Regarding the syntax, it's a union of mathematical segments, maybe missing the union symbol between the two. Each segment is closed on one side and open on the other side : `[ minvalue, maxvalue-excluded [`. Another standard for this notation is to use a parenthesis such as `[ minvalue, maxvalue-excluded )` but that wasn't known to me when I made that code.

In any case, that's definitely not very user friendly, it was mostly useful for debugging.

We are also thinking of maybe transforming `Range` into a trait at some point to deal with the current issue of pre-release versions, so that's another reason we didn't put much effort in this yet.

Is the fact that the `Display` trait is implemented annoying to you? could you manage getting more user-firendly outputs with dedicated functions like `nice_display(r: Range) -> String` or would you like to be able to implement yourself the `Display` trait?

**Comment by lpil** [comment]
Ah! Thank you for the information there. I'll close this as that answers my question. 

> Is the fact that the Display trait is implemented annoying to you?

It was a little surprising when I came across it, though I would be happy using another function to print ranges. If there are multiple output formats I would prefer to have the most widely understood one be the one used for `Display`.

Currently I am using a different range type so that I can have more control over how prereleases are handled so it doesn't impact me at all.
